### ISSUE TITLE
Looks wrong (spline count)

### ISSUE THREAD

**Issue by gitcnd** [hugokernel/OpenSCAD_ServoArms#4]
My servos have 20 notches on their splines.

You photo has too many.

**Comment by hugokernel** [comment]
Not all servo models have the same number, so there is an array that allows you to configure a servo with a different configuration (e.g. FUTABA_3F_SPLINE).

Additionally, because of the clearance of the printer and the printing, it is not useful to have the exact number to obtain a good mechanical connection, the best is to try and adapt according to your printer, your plastic.
